//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentBlock
    {
        public int Parentid { get; set; }
        public Nullable<int> Id { get; set; }
        public int PostID { get; set; }
        public string NameParentId { get; set; }
        public string NameId { get; set; }
        public string content_type { get; set; }
        public string content { get; set; }
    
        public virtual tblTinTuc tblTinTuc { get; set; }
    }
}
