//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTinTucs
    {
        public int PostID { get; set; }
        public string Title { get; set; }
        public string sContents { get; set; }
        public string Contents { get; set; }
        public string Thumb { get; set; }
        public Nullable<bool> Published { get; set; }
        public string Alias { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Author { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Tags { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<bool> isHot { get; set; }
        public Nullable<bool> isNewFeed { get; set; }
        public string MetaKey { get; set; }
        public string MetaDesc { get; set; }
        public Nullable<int> Views { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
